### ISSUE TITLE
LivePersonModule.swift Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by LayMui** [LivePersonInc/iOSFrameworks#24]
The xcode project was able to build in xcode 11.6
but after upgrade to xcode 12, it has compiler build fail

npx react-native run-ios --configuration Debug --simulator="iPhone 11" --scheme "MyApp_UAT"

DataStore -index-system-modules
/Users/app/node_modules/@dt/react-native-liveperson/ios/LivePersonModule.swift:11:8: error: module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler: /Users/app/ios/Pods/LPMessagingSDK/LPMessagingSDK/LPMessagingSDK.framework/Modules/LPMessagingSDK.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import LPMessagingSDK

**Comment by luandrecast-lp** [comment]
@LayMui not sure if you are aware but we now have support for XCFramework.
try on the latest SDK Version, it supports Swift 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53) and above.
